title: Farid Ghorbani
logo: /assets/img/photo_.jpg
description: MSIS graduate from Northeastern University with expertise in problem-solving, programming (C++, Python, Java), and web development (JavaScript, React). Experienced in data science, machine learning, and software testing with a strong background in leading technical projects and building AI-driven solutions.
show_downloads: true
theme: jekyll-theme-minimal
